# Generated by Django 3.0.10 on 2020-11-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0007_auto_20201030_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_image',
            name='WORKER_ID',
        ),
        migrations.RemoveField(
            model_name='question',
            name='IMAGE_ID',
        ),
        migrations.DeleteModel(
            name='ANSWER',
        ),
        migrations.DeleteModel(
            name='DATA_IMAGE',
        ),
        migrations.DeleteModel(
            name='DATA_WORKER',
        ),
        migrations.DeleteModel(
            name='QUESTION',
        ),
    ]
